version: "3.8"

services:
  postgres_geekhouse:
    image: postgres
    container_name: postgres_geekhouse
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dockeradmin
      - POSTGRES_DB=geekhouse_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: geekhouse_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
    